### PR TITLE
feat: initial vue plugin support

### PR DESCRIPTION
**Pull request by sibbng**

### CODE REVIEW

**Comment by antfu** [comment]
wow, you are on fire man! 👍

**Comment by antfu** [comment]
LGTM, feel free to merge when you feel it's ready, and then pin me for the release (if you'd like to do the releasing process, let me know your npm id). I'd also feel we should have some document taking about this feature. Thanks.

**Comment by sibbng** [comment]
> wow, you are on fire! 👍
😊

> LGTM, feel free to merge when you feel it's ready, and then pin me for the release (if you'd like to do the releasing process, let me know your npm id). I'd also feel we should have some document taking about this feature. Thanks.

That would be awesome. My my id is: `sibbngheid`

Thnaks for trusting me. I appreciate that. 🤗

**Comment by crutchcorn** [comment]
As someone who's never built a Vue plugin, could you help me understand what this code is doing and why it's required for this package? I'm just wanting to learn and don't quite know what to search to learn more 😅

**Comment by sibbng** [comment]
> As someone who's never built a Vue plugin, could you help me understand what this code is doing and why it's required for this package? I'm just wanting to learn and don't quite know what to search to learn more 😅

First of all reading https://v3.vuejs.org/guide/plugins.html#writing-a-plugin is heavy recommended to understand Vue's plugin API.

Most of codes in this library ported from @vue/runtime-core.

There is 2 ways to make plugins available in component tree.
- app.provide
- `provide()` in `setup()`

This PR is ported from
createApp: https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/apiCreateApp.ts
provide/inject: https://github.com/vuejs/vue-next/blob/master/packages/runtime-core/src/apiInject.ts

Example Villus:
createClient: https://github.com/logaretm/villus/blob/main/packages/villus/src/client.ts#L138
inject: https://github.com/logaretm/villus/blob/main/packages/villus/src/useQuery.ts#L39
provide: https://github.com/logaretm/villus/blob/main/packages/villus/src/useClient.ts

I hope it helps 😊

**Comment by antfu** [comment]
@sibbng you should have the permission to publish the package now. I use `npm run release` to bump the version and publishing. Create PRs or pin me when you would like me to have the review, otherwise, you can publish new versions whenever you feel it needed.

Thanks :)

**Comment by crutchcorn** [comment]
OMG I'm such a goofball. I've utilized Vue plugins before but didn't put 2 + 2 together for why `reactivue` would need a Vue plugin (it doesn't, obviously - but being able to support Vue plugins is another thing)

Thanks so much for the guidance and explanation @sibbng

**Pull request merged**
